/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as oneInch from "./oneInch";
export type { oneInch };
import type * as signature from "./signature";
export type { signature };
import type * as tokenReceiveableSol from "./tokenReceiveable.sol";
export type { tokenReceiveableSol };
import type * as uniswap from "./uniswap";
export type { uniswap };
export type { IWETH } from "./IWETH";
export type { WithAdmin } from "./WithAdmin";
